### ISSUE TITLE
back button on settings page crashes

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#118]
Notes
======
back button on settings page crashes

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0
build | 1
UDID | 2c6b08649605565
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifi
Stack trace
======
```java
java.lang.IllegalStateException: Could not find a method onBackPressed(View) in the activity class wycliffeassociates.recordingapp.SettingsPage.Settings for onClick handler on view class android.widget.ImageButton with id 'btnBack'
	at android.view.View$1.onClick(View.java:3949)
	at android.view.View.performClick(View.java:4633)
	at android.view.View$PerformClick.run(View.java:19270)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchMethodException: onBackPressed [class android.view.View]
	at java.lang.Class.getConstructorOrMethod(Class.java:472)
	at java.lang.Class.getMethod(Class.java:857)
	at android.view.View$1.onClick(View.java:3942)
	... 11 more

```

**Comment by vleong2332** [comment]
Dev error
