### ISSUE TITLE
memory?

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#191]
Notes
======
memory?

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0
build | 1
UDID | db79950d0dea80d8
Android Release | 5.1.1
Android SDK | 22
Brand | nvidia
Device | shieldtablet
Stack trace
======
```java
java.lang.OutOfMemoryError: Failed to allocate a 226852 byte allocation with 167884 free bytes and 163KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2474)
	at android.content.res.Resources.loadDrawable(Resources.java:2381)
	at android.content.res.Resources.getDrawable(Resources.java:787)
	at android.content.Context.getDrawable(Context.java:411)
	at android.view.View.setBackgroundResource(View.java:16208)
	at wycliffeassociates.recordingapp.AudioVisualization.VolumeMeter$1.run(VolumeMeter.java:71)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5273)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
Log history
======
```java
2/4/16 9:24 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 9:04 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1abe364a: passing cut to WavPlayer and Canvases
2/4/16 9:04 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/4/16 9:04 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/4/16 9:04 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@ba5b267: passing cut to WavPlayer and Canvases
2/4/16 9:04 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/4/16 9:04 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/4/16 8:59 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@c06ef03: passing cut to WavPlayer and Canvases
2/4/16 8:59 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/4/16 8:59 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/4/16 8:59 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@7b39f77: passing cut to WavPlayer and Canvases
2/4/16 8:59 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/4/16 8:59 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/4/16 8:58 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1b0919e5: Setting up visualizer
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 1978
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 639 width: 1920
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1b0919e5: Loading wav from file: /storage/emulated/0/TranslationRecorder/05a879b8-aa73-4496-a97a-21861f92e014.wav
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1b0919e5: passing cut to WavPlayer and Canvases
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1b0919e5: Connecting UImanager to marker views
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: true
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: false
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.Playback.PlaybackScreen@36dfa87c: Loading Playback screen. Recorded Filename is /storage/emulated/0/TranslationRecorder/05a879b8-aa73-4496-a97a-21861f92e014.wav Suggested Filename is en_udb_gen_49-1_1 Came from loading a file is:false
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3447ec7f: Stopping recording
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3447ec7f: Pausing recording
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3447ec7f: Starting recording
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@31fb4edd: passing cut to WavPlayer and Canvases
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/4/16 8:44 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.MainMenu@3adbd5f5: Log file initialized.
2/4/16 8:44 AM  W/wycliffeassociates.recordingapp.MainMenu@336e640d: Log file initialized.
2/4/16 8:36 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:29 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:28 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:25 AM  W/wycliffeassociates.recordingapp.MainMenu@12dd669f: Log file initialized.
2/4/16 8:21 AM  W/wycliffeassociates.recordingapp.MainMenu@12dd669f: Log file initialized.
2/4/16 8:20 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:19 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:18 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:18 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/4/16 8:16 AM  W/wycliffeassociates.recordingapp.MainMenu@21c266b8: Log file initialized.
2/3/16 4:41 PM  E/wycliffeassociates.recordingapp.MainMenu@21c266b8: ERROR: could not initialize log file.
     
```

**Comment by jsarabia1247** [comment]
Recording screen continues to put messages into queues when paused, which if left up for a long period of time will run out of memory and crash. only the writing and compression queues seem to have this.
