### ISSUE TITLE
crash report- failure to allocate bytes

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#322]
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 0.18d |
| build | 1 |
| UDID | fd7061ca513f999 |
| Android Release | 5.0.2 |
| Android SDK | 21 |
| Brand | lge |
| Device | e9wifi |
# Stack trace

``` java
java.lang.OutOfMemoryError: Failed to allocate a 12 byte allocation with 8 free bytes and 8B until OOM
    at wycliffeassociates.recordingapp.Recording.WavFileWriter$2.run(WavFileWriter.java:101)
    at java.lang.Thread.run(Thread.java:818)

```
# Log history

``` java
3/8/16 2:42 PM  W/wycliffeassociates.recordingapp.MainMenu@1d7e555b: Log file initialized.
3/8/16 2:42 PM  W/wycliffeassociates.recordingapp.MainMenu@1d7e555b: Log file initialized.
3/8/16 2:42 PM  W/wycliffeassociates.recordingapp.MainMenu@1d7e555b: Log file initialized.
3/8/16 2:42 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3df794d0: Starting recording
3/8/16 2:42 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1c30c77a: passing cut to WavPlayer and Canvases
3/8/16 2:42 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:42 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/8/16 2:41 PM  W/wycliffeassociates.recordingapp.MainMenu@3bbb4b4b: Log file initialized.
3/8/16 2:41 PM  W/wycliffeassociates.recordingapp.MainMenu@17c18f09: Log file initialized.
3/8/16 2:41 PM  W/wycliffeassociates.recordingapp.MainMenu@2c2e41f8: Log file initialized.
3/8/16 2:40 PM  W/wycliffeassociates.recordingapp.MainMenu@e953e1f: Log file initialized.
3/8/16 2:40 PM  W/wycliffeassociates.recordingapp.MainMenu@755d57d: Log file initialized.
3/8/16 1:15 PM  W/wycliffeassociates.recordingapp.MainMenu@3bbb4b4b: Log file initialized.
3/8/16 1:15 PM  W/wycliffeassociates.recordingapp.MainMenu@17c18f09: Log file initialized.
3/8/16 1:13 PM  W/wycliffeassociates.recordingapp.MainMenu@2c2e41f8: Log file initialized.
2/11/16 5:19 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f52fa95: passing cut to WavPlayer and Canvases
2/11/16 5:19 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
2/11/16 5:19 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
2/11/16 5:08 PM  W/wycliffeassociates.recordingapp.MainMenu@31d0dc4a: Log file initialized.
2/11/16 5:08 PM  W/wycliffeassociates.recordingapp.FilesPage.Export.FolderExport$StorageAccess@3af7018: Source file is /storage/emulated/0/TranslationRecorder/en_ulb_luk_07-48_01.zip
2/11/16 5:07 PM  W/wycliffeassociates.recordingapp.FilesPage.Export.FolderExport$StorageAccess@3438b46c: Source file is /storage/emulated/0/TranslationRecorder/en_ulb_luk_07-48_01.zip
2/11/16 5:04 PM  W/wycliffeassociates.recordingapp.FilesPage.Export.FolderExport$StorageAccess@2cef5725: Source file is /storage/emulated/0/TranslationRecorder/en_ulb_luk_07-48_01.zip
2/11/16 5:00 PM  W/wycliffeassociates.recordingapp.MainMenu@205a629f: Log file initialized.
2/11/16 4:45 PM  W/wycliffeassociates.recordingapp.MainMenu@3c5d7f4: Log file initialized.

```

**Comment by jsarabia1247** [comment]
iRig Studio mic attached
