### ISSUE TITLE
crash report- failure to allocate bytes

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#324]
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 0.18d |
| build | 1 |
| UDID | fd7061ca513f999 |
| Android Release | 5.0.2 |
| Android SDK | 21 |
| Brand | lge |
| Device | e9wifi |
# Stack trace

``` java
java.lang.OutOfMemoryError: Failed to allocate a 28 byte allocation with 8 free bytes and 8B until OOM
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1832)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2012)
    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:373)
    at wycliffeassociates.recordingapp.Recording.WavFileWriter$1.run(WavFileWriter.java:43)
    at java.lang.Thread.run(Thread.java:818)

```
# Log history

``` java
3/8/16 2:56 PM  W/wycliffeassociates.recordingapp.MainMenu@2a262bc: Log file initialized.
3/8/16 2:55 PM  W/wycliffeassociates.recordingapp.MainMenu@2a262bc: Log file initialized.
3/8/16 2:55 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@9964157: Starting recording
3/8/16 2:54 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@321200fa: passing cut to WavPlayer and Canvases
3/8/16 2:54 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:54 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/8/16 2:54 PM  W/wycliffeassociates.recordingapp.MainMenu@2a262bc: Log file initialized.
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@323d845a: Stopping recording
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@323d845a: Pausing recording
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@323d845a: Starting recording
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@38cf05b4: passing cut to WavPlayer and Canvases
3/8/16 2:51 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:51 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.MainMenu@4fab4fd: Log file initialized.
3/8/16 2:51 PM  W/wycliffeassociates.recordingapp.MainMenu@2a262bc: Log file initialized.
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@13bd5a6d: passing cut to WavPlayer and Canvases
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.MainMenu@36a78ab7: Log file initialized.
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@353615ae: Setting up visualizer
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 10524
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 519 width: 1280
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@353615ae: Loading wav from file: /storage/emulated/0/TranslationRecorder/daa13b8e-1349-4a2f-9db7-d6544f32d916.wav
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@353615ae: passing cut to WavPlayer and Canvases
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@353615ae: Connecting UImanager to marker views
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: true
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: false
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.Playback.PlaybackScreen@35d38268: Loading Playback screen. Recorded Filename is /storage/emulated/0/TranslationRecorder/daa13b8e-1349-4a2f-9db7-d6544f32d916.wav Suggested Filename is en_ulb_luk_07-01_01 Came from loading a file is:false
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@83a72e4: Stopping recording
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@83a72e4: Pausing recording
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@83a72e4: Starting recording
3/8/16 2:47 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@13bd5a6d: passing cut to WavPlayer and Canvases
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:47 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/8/16 2:46 PM  W/wycliffeassociates.recordingapp.MainMenu@36a78ab7: Log file initialized.
3/8/16 2:46 PM  W/wycliffeassociates.recordingapp.MainMenu@1d7e555b: Log file initialized.
3/8/16 2:45 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3de834e2: Stopping recording
3/8/16 2:45 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3de834e2: Pausing recording
3/8/16 2:45 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@3de834e2: Starting recording
3/8/16 2:45 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@38c1d200: passing cut to WavPlayer and Canvases
3/8/16 2:45 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
3/8/16 2:45 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true

```

**Comment by jsarabia1247** [comment]
iRig Studio mic attached
