### ISSUE TITLE
crash report- unable to start recording service

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#325]
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 0.18d |
| build | 1 |
| UDID | eabfea66385fed22 |
| Android Release | 5.0.1 |
| Android SDK | 21 |
| Brand | Lenovo |
| Device | A10-70F |
# Stack trace

``` java
java.lang.RuntimeException: Unable to start service wycliffeassociates.recordingapp.Recording.WavRecorder@2545dabd with Intent { cmp=wycliffeassociates.recordingapp/.Recording.WavRecorder }: java.lang.IllegalArgumentException
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3063)
    at android.app.ActivityThread.access$2100(ActivityThread.java:167)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5534)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.lang.IllegalArgumentException
    at android.media.AudioRecord.<init>(AudioRecord.java:277)
    at android.media.AudioRecord.<init>(AudioRecord.java:233)
    at wycliffeassociates.recordingapp.Recording.WavRecorder.record(WavRecorder.java:54)
    at wycliffeassociates.recordingapp.Recording.WavRecorder.onStartCommand(WavRecorder.java:40)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3046)
    ... 9 more

```
# Log history

``` java
3/9/16 4:43 AM  W/wycliffeassociates.recordingapp.MainMenu@2edbb832: Log file initialized.
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Rewriting file to disk due to cuts
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 26490ms which is location 2336418
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 26492ms which is location 2336594
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 26509ms which is location 2338092
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 26673ms which is location 2352558
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 27008ms which is location 2382104
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 27289ms which is location 2406888
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 27700ms which is location 2443140
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 27994ms which is location 2469070
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28313ms which is location 2497206
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28630ms which is location 2525166
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28880ms which is location 2547216
3/9/16 4:30 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29086ms which is location 2565384
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Updating UI after cut
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Reinitializing minimap
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Cutting from 29088 to 29376
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@3df3d4e9: Generating location stacks
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@3df3d4e9: Generating flattened stack and computing time removed
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Pushing cut to stack. Start is 29088 End is 29376
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29088ms which is location 2565560
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29376ms which is location 2590962
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29373ms which is location 2590698
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29368ms which is location 2590256
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29361ms which is location 2589640
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29356ms which is location 2589198
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29349ms which is location 2588580
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29344ms which is location 2588140
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29341ms which is location 2587876
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29336ms which is location 2587434
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29332ms which is location 2587082
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29327ms which is location 2586640
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29322ms which is location 2586200
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29316ms which is location 2585670
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29310ms which is location 2585142
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29299ms which is location 2584170
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29270ms which is location 2581614
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29229ms which is location 2577996
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29196ms which is location 2575086
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29175ms which is location 2573234
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29138ms which is location 2569970
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29088ms which is location 2565560
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29083ms which is location 2565120
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29079ms which is location 2564766
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29071ms which is location 2564062
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29060ms which is location 2563092
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29048ms which is location 2562032
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29034ms which is location 2560798
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29021ms which is location 2559652
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29003ms which is location 2558064
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28983ms which is location 2556300
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28968ms which is location 2554976
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28954ms which is location 2553742
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28941ms which is location 2552596
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28936ms which is location 2552154
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28932ms which is location 2551802
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28930ms which is location 2551626
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28929ms which is location 2551536
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28933ms which is location 2551890
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28944ms which is location 2552860
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28958ms which is location 2554094
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 28996ms which is location 2557446
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29038ms which is location 2561150
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29086ms which is location 2565384
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29160ms which is location 2571912
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29225ms which is location 2577644
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29299ms which is location 2584170
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29425ms which is location 2595284
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29444ms which is location 2596960
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29455ms which is location 2597930
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29458ms which is location 2598194
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29462ms which is location 2598548
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29490ms which is location 2601018
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29514ms which is location 2603134
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29584ms which is location 2609308
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29675ms which is location 2617334
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29733ms which is location 2622450
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29875ms which is location 2634974
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 29954ms which is location 2641942
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30123ms which is location 2656848
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30220ms which is location 2665404
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30316ms which is location 2673870
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30403ms which is location 2681544
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30504ms which is location 2690452
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 30601ms which is location 2699008
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 1439ms which is location 126918
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 1427ms which is location 125860
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 1340ms which is location 118188
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 995ms which is location 87758
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 595ms which is location 52478
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 39ms which is location 3438
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to 5ms which is location 440
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -2ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -1ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -44ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -168ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -168ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -227ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -306ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -437ms which is location 0
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.WavPlayer@3c496104: Seeking to -38ms which is location 0
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Setting up visualizer
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 30601
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 769 width: 1920
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Could not find a matching vis file, creating...
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Loading wav from file: /storage/emulated/0/TranslationRecorder/en_udb_jud_01-24_11.wav
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: passing cut to WavPlayer and Canvases
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2f19b47d: Connecting UImanager to marker views
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: true
3/9/16 4:29 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/9/16 4:29 AM  W/wycliffeassociates.recordingapp.Playback.PlaybackScreen@ddee3dc: Loading Playback screen. Recorded Filename is /storage/emulated/0/TranslationRecorder/en_udb_jud_01-24_11.wav Suggested Filename is en_udb_jud_01-24_11 Came from loading a file is:true
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@9fe5fe: Setting up visualizer
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 16924
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 769 width: 1920
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Could not find a matching vis file, creating...
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@9fe5fe: Loading wav from file: /storage/emulated/0/TranslationRecorder/en_udb_jud_01-22_10.wav
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@9fe5fe: passing cut to WavPlayer and Canvases
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@9fe5fe: Connecting UImanager to marker views
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: true
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.Playback.PlaybackScreen@1bd50ca1: Loading Playback screen. Recorded Filename is /storage/emulated/0/TranslationRecorder/en_udb_jud_01-22_10.wav Suggested Filename is en_udb_jud_01-22_10 Came from loading a file is:true
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2d1b74bb: Setting up visualizer
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 20864
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 769 width: 1920
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Could not find a matching vis file, creating...
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2d1b74bb: Loading wav from file: /storage/emulated/0/TranslationRecorder/en_udb_jud_01-20_09.wav
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2d1b74bb: passing cut to WavPlayer and Canvases
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@2d1b74bb: Connecting UImanager to marker views
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: true
3/9/16 4:28 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Is a loaded file: true
3/9/16 4:28 AM  W/wycliffeassociates.recordingapp.Playback.PlaybackScreen@3f295292: Loading Playback screen. Recorded Filename is /storage/emulated/0/TranslationRecorder/en_udb_jud_01-20_09.wav Suggested Filename is en_udb_jud_01-20_09 Came from loading a file is:true
3/9/16 4:27 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
3/9/16 4:27 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Created a BMP
3/9/16 4:27 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.MinimapView: Saving minimap to BMP
3/9/16 4:27 AM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@580eec4: Setting up visualizer
3/9/16 4:27 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Loaded file duration in ms is: 27941
3/9/16 4:27 AM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: MainWave height: 769 width: 1920

```

**Comment by jsarabia1247** [comment]
iRig Studio mic attached
