### ISSUE TITLE
rotating screen when setting up a new project

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#606]
# Notes

rotating screen when setting up a new project
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 0.8.5 |
| build | 1 |
| UDID | ef690994c812b74f |
| Android Release | 5.0.1 |
| Android SDK | 21 |
| Brand | Lenovo |
| Device | A10-70F |
# Stack trace

``` java
java.lang.RuntimeException: Unable to start activity ComponentInfo{wycliffeassociates.recordingapp/wycliffeassociates.recordingapp.ProjectManager.ActivityProjectManager}: java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4118)
    at android.app.ActivityThread.access$900(ActivityThread.java:167)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5534)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference
    at android.app.BackStackRecord.run(BackStackRecord.java:815)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
    at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
    at wycliffeassociates.recordingapp.ProjectManager.ActivityProjectManager.onCreate(ActivityProjectManager.java:108)
    at android.app.Activity.performCreate(Activity.java:5971)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
    ... 11 more

```
# Log history

``` java
9/13/16 8:16 AM  W/wycliffeassociates.recordingapp.MainMenu@196a12e5: SUCCESS: Log file initialized.
9/13/16 8:16 AM  W/wycliffeassociates.recordingapp.MainMenu@389876b1: SUCCESS: Log file initialized.
9/12/16 3:49 PM  W/wycliffeassociates.recordingapp.MainMenu@3fd7ad27: SUCCESS: Log file initialized.
9/12/16 3:49 PM  W/wycliffeassociates.recordingapp.MainMenu@3fd7ad27: SUCCESS: Visualization folder exists.
9/12/16 3:43 PM  W/wycliffeassociates.recordingapp.MainMenu@2a832d11: SUCCESS: Log file initialized.
9/12/16 3:43 PM  W/wycliffeassociates.recordingapp.MainMenu@2a832d11: SUCCESS: Visualization folder exists.
9/12/16 3:42 PM  W/wycliffeassociates.recordingapp.MainMenu@180e77eb: SUCCESS: Log file initialized.
9/12/16 3:42 PM  W/wycliffeassociates.recordingapp.MainMenu@180e77eb: SUCCESS: Visualization folder exists.
9/12/16 3:40 PM  W/wycliffeassociates.recordingapp.MainMenu@389876b1: SUCCESS: Log file initialized.
9/9/16 1:21 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager$3@1d60f075: UI thread received a stop message
9/9/16 1:17 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@23c4104d: passing cut to WavPlayer and Canvases
9/9/16 1:17 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
9/9/16 1:17 PM  W/wycliffeassociates.recordingapp.MainMenu@394b5e51: SUCCESS: Log file initialized.
9/9/16 1:17 PM  W/wycliffeassociates.recordingapp.MainMenu@394b5e51: SUCCESS: Visualization folder exists.
9/9/16 1:15 PM  W/wycliffeassociates.recordingapp.MainMenu@956c434: SUCCESS: Log file initialized.
9/9/16 1:15 PM  W/wycliffeassociates.recordingapp.MainMenu@956c434: SUCCESS: Visualization folder exists.
9/9/16 1:15 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager$3@131274dc: UI thread received a stop message
9/9/16 1:14 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1f4ec167: passing cut to WavPlayer and Canvases
9/9/16 1:14 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
9/9/16 1:14 PM  W/wycliffeassociates.recordingapp.MainMenu@389876b1: SUCCESS: Log file initialized.
9/9/16 1:12 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1f4ec167: passing cut to WavPlayer and Canvases
9/9/16 1:12 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false
9/9/16 1:12 PM  W/wycliffeassociates.recordingapp.MainMenu@389876b1: SUCCESS: Log file initialized.
9/9/16 1:11 PM  W/wycliffeassociates.recordingapp.AudioVisualization.UIDataManager@1d47c975: passing cut to WavPlayer and Canvases
9/9/16 1:11 PM  W/class wycliffeassociates.recordingapp.AudioVisualization.UIDataManager: Playback mode: false

```

**Comment by jsarabia1247** [comment]
Cannot duplicate. Unsure of how to address the actual crash; may not be present in latest version.

Other issues with screen rotation do occur: maintaining position on screen rotation, rotation on source audio page prevents the user from backing out, continue or skip after rotation on source audio page causes a crash.
