### ISSUE TITLE
crash on opening new recording

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#708]
Notes
======
crash on opening new recording

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0.0- Beta
build | 1
UDID | 805543ae309546ac
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{wycliffeassociates.recordingapp/wycliffeassociates.recordingapp.Recording.RecordingScreen}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.StringReader.<init>(StringReader.java:47)
	at com.wycliffeassociates.io.LanguageLevel.parseJSON(LanguageLevel.java:25)
	at com.wycliffeassociates.io.ArchiveOfHolding$Header.<init>(ArchiveOfHolding.java:48)
	at com.wycliffeassociates.io.ArchiveOfHolding.<init>(ArchiveOfHolding.java:109)
	at wycliffeassociates.recordingapp.Playback.SourceAudio.getAudioFromUri(SourceAudio.java:125)
	at wycliffeassociates.recordingapp.Playback.SourceAudio.loadAudioFile(SourceAudio.java:173)
	at wycliffeassociates.recordingapp.Playback.SourceAudio.initSrcAudio(SourceAudio.java:188)
	at wycliffeassociates.recordingapp.Recording.RecordingScreen.onCreate(RecordingScreen.java:120)
	at android.app.Activity.performCreate(Activity.java:6020)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
	... 10 more

```
Log history
======
```java
12/20/16 8:36 AM  W/wycliffeassociates.recordingapp.MainMenu@c24c16b: SUCCESS: Log file initialized.
12/20/16 8:36 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager@db1cd81: passing cut to BufferPlayer and Canvases
12/20/16 8:36 AM  W/class wycliffeassociates.recordingapp.Playback.player.UIDataManager: Playback mode: false
12/20/16 8:36 AM  W/wycliffeassociates.recordingapp.MainMenu@22914efd: SUCCESS: Log file initialized.
12/16/16 11:29 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@73613a2: Refreshing take rating for en_ulb_b58_phm_c01_v01-03_t05.wav
12/16/16 11:28 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@73613a2: Refreshing take rating for en_ulb_b58_phm_c01_v01-03_t05.wav
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@380228ff: Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@380228ff: Project: language en book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@380228ff: Project: language en book mat version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@380228ff: Recent Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book mat version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Recent Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager$3@2252e17f: UI thread received a stop message
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager@eb73352: passing cut to BufferPlayer and Canvases
12/16/16 11:27 AM  W/class wycliffeassociates.recordingapp.Playback.player.UIDataManager: Playback mode: false
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book phm version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book mat version ulb mode chunk
12/16/16 11:27 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Recent Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book phm version ulb mode chunk
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Project: language en book mat version ulb mode chunk
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1721523e: Recent Project: language cmn-x-omc book phm version ulb mode chunk
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager$3@266287c9: UI thread received a stop message
12/16/16 11:26 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager@29f446f6: passing cut to BufferPlayer and Canvases
12/16/16 11:26 AM  W/class wycliffeassociates.recordingapp.Playback.player.UIDataManager: Playback mode: false
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book phm version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book mat version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book phm version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book mat version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language cmn book oba version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book phm version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Project: language en book mat version ulb mode chunk
12/16/16 11:24 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@3e275112: Recent Project: language cmn book oba version ulb mode chunk
12/16/16 11:23 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager$3@2311d6dd: UI thread received a stop message
12/16/16 11:23 AM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager@1771c825: passing cut to BufferPlayer and Canvases
12/16/16 11:23 AM  W/class wycliffeassociates.recordingapp.Playback.player.UIDataManager: Playback mode: false
12/16/16 11:22 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@115677c8: Project: language en book phm version ulb mode chunk
12/16/16 11:22 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@115677c8: Project: language en book mat version ulb mode chunk
12/16/16 11:22 AM  W/wycliffeassociates.recordingapp.MainMenu@129de7f2: SUCCESS: Log file initialized.
     
```

**Comment by jsarabia1247** [comment]
attempted to open an invalidly formed tr file (maybe an old version?)
