### ISSUE TITLE
playing back after2 cuts

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#723]
Notes
======
playing back after2 cuts

Environment
======
Environment Key | Value
:----: | :----:
version | 0.8.6 Dec 12
build | 1
UDID | 7c1abfb9150b38df
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.nio.BufferUnderflowException
	at java.nio.ByteBufferAsShortBuffer.get(ByteBufferAsShortBuffer.java:87)
	at wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider.getWithSkips(AudioBufferProvider.java:128)
	at wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider.get(AudioBufferProvider.java:77)
	at wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider.onBufferRequested(AudioBufferProvider.java:70)
	at wycliffeassociates.recordingapp.Playback.player.BufferPlayer$1.run(BufferPlayer.java:67)

```
Log history
======
```java
1/3/17 10:38 PM  W/wycliffeassociates.recordingapp.MainMenu@1364798f: SUCCESS: Log file initialized.
1/3/17 10:37 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating location stacks
1/3/17 10:37 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating flattened stack and computing time removed
1/3/17 10:37 PM  E/wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider@2dee0cbd: Paused right at the limit
1/3/17 10:37 PM  E/wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider@2dee0cbd: Paused right at the limit
1/3/17 10:37 PM  E/wycliffeassociates.recordingapp.Playback.player.AudioBufferProvider@2dee0cbd: Paused right at the limit
1/3/17 10:37 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating location stacks
1/3/17 10:37 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating flattened stack and computing time removed
1/3/17 10:37 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating flattened stack and computing time removed
1/3/17 10:36 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating location stacks
1/3/17 10:36 PM  W/wycliffeassociates.recordingapp.Playback.Editing.CutOp@948a205: Generating flattened stack and computing time removed
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@ab5501f: SUCCESS: exited queues, took 37 to finish writing
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: Compression queue finishing, sending done message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: exited compression thread loop
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: Compression thread closed file
1/3/17 10:35 PM  E/wycliffeassociates.recordingapp.Recording.WavFileWriter$1@1b0b2417: raw audio queue finishing, sending done message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: Compression thread writing remaining data
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$1@1b0b2417: raw audio thread exited loop
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: Compression thread received a stop message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$1@1b0b2417: raw audio thread received a stop message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager$3@23b1b9ed: UI thread received a stop message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@ab5501f: Stopping recording
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: Compression thread received a onPause message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$1@1b0b2417: raw audio thread received a onPause message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@ab5501f: Pausing recording
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: created a new vis file
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.WavFileWriter$2@189d0096: starting compression thread
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager$3@2496bf6c: UI thread received a stop message
1/3/17 10:35 PM  W/wycliffeassociates.recordingapp.Recording.RecordingScreen@ab5501f: Starting recording
1/3/17 10:34 PM  W/wycliffeassociates.recordingapp.Playback.player.UIDataManager@2b736fa4: passing cut to BufferPlayer and Canvases
1/3/17 10:34 PM  W/class wycliffeassociates.recordingapp.Playback.player.UIDataManager: Playback mode: false
1/3/17 10:32 PM  W/wycliffeassociates.recordingapp.MainMenu@1364798f: SUCCESS: Log file initialized.
1/3/17 10:25 PM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book luk version ulb mode chunk
1/3/17 10:25 PM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book gen version ulb mode chunk
12/15/16 3:53 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book luk version ulb mode chunk
12/15/16 3:53 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book gen version ulb mode chunk
12/13/16 3:31 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
12/13/16 3:31 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@1e145115: Refreshing take rating for en_ulb_b43_luk_c21_v01-04_t01.wav
12/13/16 3:31 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Could not find a matching vis file, creating...
12/13/16 3:31 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@1e145115: Refreshing take rating for en_ulb_b43_luk_c21_v01-04_t01.wav
12/13/16 3:31 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@1fd5f52b: Refreshing take rating for en_ulb_b43_luk_c03_v01-02_t01.wav
12/13/16 3:31 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Finished creating a vis file
12/13/16 3:31 AM  W/class wycliffeassociates.recordingapp.WavFileLoader: Could not find a matching vis file, creating...
12/13/16 3:31 AM  W/wycliffeassociates.recordingapp.widgets.UnitCard@1fd5f52b: Refreshing take rating for en_ulb_b43_luk_c03_v01-02_t01.wav
12/13/16 3:30 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book luk version ulb mode chunk
12/13/16 3:30 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book gen version ulb mode chunk
12/13/16 3:17 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book luk version ulb mode chunk
12/13/16 3:17 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book gen version ulb mode chunk
12/13/16 3:17 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book luk version ulb mode chunk
12/13/16 3:17 AM  W/wycliffeassociates.recordingapp.ProjectManager.activities.ActivityProjectManager@1bee8c66: Project: language en book gen version ulb mode chunk
12/13/16 3:16 AM  W/wycliffeassociates.recordingapp.MainMenu@f2efc5a: SUCCESS: Log file initialized.
     
```

**Comment by jsarabia1247** [comment]
already fixed, old version
