### ISSUE TITLE
samsung s7

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#807]
Notes
======
samsung s7

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0.2 Beta
build | 7
UDID | b986a18d8a9f077
Android Release | 6.0.1
Android SDK | 23
Brand | samsung
Device | heroqltespr
Stack trace
======
```java
java.lang.NullPointerException: Attempt to get length of null array
	at org.wycliffeassociates.translationrecorder.ProjectManager.tasks.resync.ProjectListResyncTask.getAllProjects(ProjectListResyncTask.java:38)
	at org.wycliffeassociates.translationrecorder.ProjectManager.tasks.resync.ProjectListResyncTask.run(ProjectListResyncTask.java:75)
	at java.lang.Thread.run(Thread.java:818)

```
Log history
======
```java
1/29/17 18:35  W/org.wycliffeassociates.translationrecorder.MainMenu@23d3608: SUCCESS: Log file initialized.
1/29/17 18:34  W/org.wycliffeassociates.translationrecorder.MainMenu@9c60569: SUCCESS: Log file initialized.
     
```

**Comment by jsarabia1247** [comment]
fixed in 1.0.3 beta
