### ISSUE TITLE
luk

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#835]
Notes
======
luk

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0.4 Beta
build | 9
UDID | 907b269f8855b31d
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wycliffeassociates.translationrecorder/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityUnitList}: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.access$800(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
	at java.lang.String.startEndAndLength(String.java:504)
	at java.lang.String.substring(String.java:1333)
	at org.wycliffeassociates.translationrecorder.Utils.capitalizeFirstLetter(Utils.java:53)
	at org.wycliffeassociates.translationrecorder.widgets.UnitCard.<init>(UnitCard.java:71)
	at org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityUnitList.prepareUnitCardData(ActivityUnitList.java:184)
	at org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityUnitList.onCreate(ActivityUnitList.java:110)
	at android.app.Activity.performCreate(Activity.java:5971)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more

```
Log history
======
```java
2/13/17 8:08 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@3474c292: SUCCESS: Log file initialized.
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book luk version ulb mode 
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1jn version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 2pe version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1th version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 2th version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1pe version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book eph version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Recent Project: language en book 1jn version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book luk version ulb mode 
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1jn version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 2pe version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1th version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 2th version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book 1pe version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Project: language en book eph version ulb mode chunk
2/13/17 8:05 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@1efe6d00: Recent Project: language en book 1jn version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@3474c292: SUCCESS: Log file initialized.
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book luk version ulb mode 
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1jn version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 2pe version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1th version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 2th version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1pe version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book eph version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Recent Project: language en book 1jn version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book luk version ulb mode 
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1jn version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 2pe version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1th version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 2th version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book 1pe version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Project: language en book eph version ulb mode chunk
2/13/17 8:00 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2b5d592c: Recent Project: language en book 1jn version ulb mode chunk
     
```

**Comment by jsarabia** [comment]
no recording mode attached to the project?
